version: '3.4'
services:

    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        networks:
            - bubble
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_BROKER_ID: 1
            KAFKA_GOUP_ID: clean-arch
        networks:
            - bubble
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper

networks:
    bubble:
        external: true